### ISSUE TITLE
Bug [HTTPS Error: [Errno 32] Broken pipe]

### ISSUE THREAD

**Issue by JSFuncks** [lilmond/sudos#3]
Hello @lilmond 
Something wrong, when i try to hit  some target i got error
HTTP Error: [Errno 32] Broken pipe  // HTTPS Error: [Errno 32] Broken pipe

and it seems not to send requests, it only sends 200-500 in dstat for the first time

python3 sudos.py https://beta.welovecloudflare.de  ./proxies/socks4/1.txt socks4 -m POST -t 500

also, the proxy function does not seem to work,  im hiting  iplogger.ru  and when i check here show just the vps ip, one ip

`Threads: 100     HR/s: 0       kB/s: 0.00
Threads: 100     HR/s: 0       kB/s: 0.00
[08:07:28] HTTP Error: [Errno 32] Broken pipe

[08:07:28] HTTP Error: [Errno 32] Broken pipe
`

**Comment by lilmond** [comment]
Hi @JSFuncks 

Thank you for reporting these issues, we'll definitely work on it soon!

```it seems not to send requests, it only sends 200-500 in dstat for the first time``` 

**This also mostly happens when:**

- A DDoS protection provider like Cloudflare blocks HTTP requests or even socket connections from you which we're still figuring out to bypass them.
- The proxy lists you provided are dead.

Once again, thanks for reporting these issues, we really appreciate it. We're doing our bests to make this tool better. We'll also be going to release the official `v1.0 (not beta)` soon. Have a nice one!

`==QIDV0UDByb0BSZt92YsV2dgwCdzFWZsBCdv5GI0VnYgQ3chxGIk5WQ`

**Comment by JSFuncks** [comment]
> Hi @JSFuncks
> 
> Thank you for reporting these issues, we'll definitely work on it soon!
> 
> `it seems not to send requests, it only sends 200-500 in dstat for the first time`
> 
> **This also mostly happens when:**
> 
> * A DDoS protection provider like Cloudflare blocks HTTP requests or even socket connections from you which we're still figuring out to bypass them.
> * The proxy lists you provided are dead.
> 
> Once again, thanks for reporting these issues, we really appreciate it. We're doing our bests to make this tool better. We'll also be going to release the official `v1.0 (not beta)` soon. Have a nice one!
> 
> `==QIDV0UDByb0BSZt92YsV2dgwCdzFWZsBCdv5GI0VnYgQ3chxGIk5WQ`

using ratelimit can bypass some waf, sending like 50-100 req /each ip i think
also when attack a target like https://target-com/test?wl2l1  to replace the path with ''/'' or detect random pages
other sugestion, making a function to auto replace proxies, auto download from https://github.com/roosterkid/openproxylist

==QIDV0UDByb0BSZt92YsV2dgwCdzFWZsBCdv5GI0VnYgQ3chxGIk5WQ this is a hash ? it look like base64 but can't decode

**Comment by JSFuncks** [comment]
Do u think is possible to improve script using that lib https://github.com/KikoTheDon/hCaptcha-Solver-Dumper ? to update it and create a func for bypassing hcaptcha ?
